/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.Dependencias;
import java.util.List;
import Clase.AdministradorDependencias;
import Clase.Dependencias;
import GUI.InicioForm;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import Controlador.DependenciasController;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import java.util.prefs.Preferences;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Lissette
 */
public class DependenciaForm extends javax.swing.JInternalFrame {
    ArrayList<Dependencias> area = new ArrayList<Dependencias>();
    private AdministradorDependencias administradorDependencias;
    int id_user;
    Dependencias dep = new Dependencias();
    DependenciasController depController = new DependenciasController();
    /**
     * Creates new form Dependencia
     */
    public DependenciaForm() {
        initComponents(); 
        CrearModelo(); 
        Preferences prefs = Preferences.userNodeForPackage(InicioForm.class);
        this.id_user = prefs.getInt("id", 0);
        administradorDependencias = new AdministradorDependencias();
        desabilitar_botones();
        jTableDependencias.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = jTableDependencias.getSelectedRow();
                    jButtonEditar.setEnabled(selectedRow != -1); // Habilitar el botón 
                    //jButtonEliminar.setEnabled(selectedRow != -1); 
                    jButtonGuardar.setEnabled(false);
                }
            }
        });
    }
    
    public void desabilitar_botones(){
        jButtonEditar.setEnabled(false); 
        jButtonGuardar.setEnabled(false);
        jButtonEliminar.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelAgenda = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabelBuscar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDependencias = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Dependencias");
        setFocusable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jButtonNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonNuevoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonNuevoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButtonNuevo)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardar)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabelAgenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAgenda.setText("Dependencias");

        jLabelId.setText("ID:");

        txt_id.setEnabled(false);

        jLabelNombre.setText("Nombre:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_id))
                    .addComponent(jLabelAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAgenda)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });

        jLabelBuscar.setText("Buscar:");

        jTableDependencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDependencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDependenciasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDependencias);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            // TODO add your handling code here:
            editar();
        }  catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    public void editar() throws Exception{
        try {
            dep.setNombre(this.jTextFieldNombre.getText());
            dep.setId(Integer.parseInt(this.txt_id.getText()));
            String nombre = this.jTextFieldNombre.getText().trim(); 
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El campo Nombre no puede estar vacío");
            } else {
                //int msg_alert = JOptionPane.showConfirmDialog(this, "¿Está seguro de modificar?", "Modificar Dependencia", JOptionPane.YES_NO_OPTION);
                Object[] options = {"Aceptar", "Cancelar"};
                int msg_alert = JOptionPane.showOptionDialog(this, "¿Está seguro de modificar?", "Modificar Dependencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            
                if(msg_alert==0){
                    depController.editarDependencia(dep);
                    JOptionPane.showMessageDialog(rootPane, "Dependencia modificada exitosamente", "Confirmación", JOptionPane.INFORMATION_MESSAGE );
                    CrearModelo();
                    limpiarCampos();
                }
                limpiarCampos();     
                nueva_dependencia();
            }  
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        // TODO add your handling code here:
        String textoBusqueda = jTextFieldBuscar.getText().trim();
        buscarDependecia(textoBusqueda);
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        try {
            insertar();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        try {
           // eliminar();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTableDependenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDependenciasMouseClicked
        // TODO add your handling code here:
        llenarTabla();
    }//GEN-LAST:event_jTableDependenciasMouseClicked

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
        nueva_dependencia();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNuevoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoKeyPressed

    private void jButtonNuevoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNuevoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoKeyReleased
    
    public void nueva_dependencia(){
        jButtonGuardar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonEliminar.setEnabled(false);
        if (jTableDependencias.getSelectedRow() != -1) {
            jTableDependencias.clearSelection();
        }
        limpiarCampos();

    }
    
    //borrado logico
    public void eliminar(int id){
        try {
            
            int filaSeleccionada = jTableDependencias.getSelectedRow(); // Obtiene la fila seleccionada
            Object estadoActtual=0;
            if (filaSeleccionada != -1) { // Verifica si se ha seleccionado alguna fila
                estadoActtual = jTableDependencias.getValueAt(filaSeleccionada, 2); // Obtiene el valor de la columna 3 (índice 2)
            }
            //System.out.print(estadoActtual);
            boolean status=false;
            if(estadoActtual=="Inactivo"){
                status=true;
            }
            String msjPregunta = status ? "ACTIVAR" : "DESACTIVAR";
            String msjRespuesta = status ? "activado" : "desactivado";
            dep.setId(Integer.parseInt(this.txt_id.getText()));
            Object[] options = {"Aceptar", "Cancelar"};
            int msg_alert = JOptionPane.showOptionDialog(this, "¿Está seguro de " + msjPregunta + "?", "Eliminar Dependencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if(msg_alert==0){
                depController.eliminarDependencia(dep);
                JOptionPane.showMessageDialog(rootPane, "Dependencia "+ msjRespuesta +" exitosamente", "Confirmación", JOptionPane.INFORMATION_MESSAGE );
                CrearModelo();
                limpiarCampos();
            }
            limpiarCampos();
            nueva_dependencia();
        } catch (Exception e) {
        }
    }

    DefaultTableModel Modelo;
    private void CrearModelo() {
       // String [] col = {"ID", "Nombre" };
        Object[] obj = new Object[6];
        try {
            Modelo = (new DefaultTableModel(null, new String[]{
                "#", "Dependencia", "Estado", "Creado por", "Fecha_registro","Acción"}) {});
            jTableDependencias.setModel(Modelo);
            
            List ls;
            String estado;
            ls = depController.mostrarDependencias();
            for (int i = 0 ; i < ls.size() ; i++) {
                dep = (Dependencias)ls.get(i);
                obj[0] =dep.getId();
                obj[1]=dep.getNombre(); 
                if(dep.isEstado()){
                    estado="Activo" ;
                }else{
                    estado="Inactivo";
                }
                obj[2]=estado; 
                obj[3]=dep.getCreated_by(); 
                obj[4]=dep.getCreated_at(); 
                jTableDependencias.getColumnModel().getColumn(5).setCellRenderer(new btnEliminarTable());
                jTableDependencias.getColumnModel().getColumn(5).setCellEditor(new ButtonEditor());
 
                jTableDependencias.setRowHeight(20);
   
                Modelo.addRow(obj);    
            }
            ls=depController.mostrarDependencias();
            this.jTableDependencias.setModel(Modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private class ButtonEditor extends DefaultCellEditor {
        private JButton button;
        private int clickedRow;

        public ButtonEditor() {
            super(new JTextField()); 

            button = new JButton(); // Creamos el botón sin un ícono inicialmente
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int row = jTableDependencias.getSelectedRow(); 
                    if (row != -1) {
                        int id = (int) jTableDependencias.getValueAt(row, 0);
                        eliminar(id);
                        //JOptionPane.showMessageDialog(null, "Button clicked at row " + row + ", ID: " + id);
                    }
                }
            });
            button.setFocusable(false);
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            clickedRow = row; 
            Object estadoActual = table.getValueAt(row, 2);
            if ("Activo".equals(estadoActual)) {
                button.setIcon(new ImageIcon("src/Imagenes/activar.png"));
            } else {
                button.setIcon(new ImageIcon("src/Imagenes/desactivar.png"));
            }

            return button;
        }

        @Override
        public Object getCellEditorValue() {
            return null; 
        }
    }
    
    private class btnEliminarTable extends DefaultTableCellRenderer {
        private JButton button;

        public btnEliminarTable() {
            button = new JButton();
            button.setBorderPainted(false); // Para quitar el borde del botón
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Object estadoActual = table.getValueAt(row, 2); // Obtener el estado actual de la fila (columna 2)

            if ("Activo".equals(estadoActual)) {
                button.setIcon(new ImageIcon("src/Imagenes/activar.png"));
            } else {
                button.setIcon(new ImageIcon("src/Imagenes/desactivar.png"));
            }

            return button;
        }
    }

    
    private void limpiarCampos() {
        jTextFieldNombre.setText("");
        txt_id.setText("");
    }
    
    
    private void buscarDependecia(String textoBusqueda) {
        DefaultTableModel modelo = (DefaultTableModel) jTableDependencias.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        jTableDependencias.setRowSorter(sorter);
        if (textoBusqueda.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + textoBusqueda));
        }
    }
    public void llenarTabla(){
        int fila= this.jTableDependencias.getSelectedRow();
        this.txt_id.setText(String.valueOf(this.jTableDependencias.getValueAt(fila, 0)));
        this.jTextFieldNombre.setText(String.valueOf(this.jTableDependencias.getValueAt(fila, 1)));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDependencias;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

    public void insertar() throws Exception{
        String nombre = this.jTextFieldNombre.getText().trim(); 
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Nombre no puede estar vacío");
        } else {
            dep.setNombre(this.jTextFieldNombre.getText());
            depController.insertarDependencias(dep, this.id_user);
            JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
            limpiarCampos();
        }
    }
    
    
}
